version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 37182635
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 37182635
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A blog worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 37182635
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - web
      - redis