name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:  # Use a descriptive name for the service
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 37182635
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      env:
        DB_HOST: postgres  # Use the service name as the HOST
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: 37182635
      run: |
        python manage.py migrate
    - name: Run tests
      run: |
        python manage.py test