name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 37182635
        ports:
          - 5432:5432
        # Set health checks to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check PostgreSQL Connection
      run: |
        apt-get update && apt-get install -y postgresql-client
        psql -h postgres -U postgres -c 'SELECT 1;'
    - name: Run migrations
      env:
        DB_HOST: postgres
        DB_PASSWORD: 37182635
        DB_NAME: postgres
        DB_USER: postgres
      run: |
        python manage.py migrate
    - name: Run tests
      run: |
        python manage.py test